# Generated by Django 4.0.4 on 2022-06-17 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='PostPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postplaces', to='posts.place')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postplaces', to='posts.post')),
            ],
            options={
                'db_table': 'postplaces',
            },
        ),
    ]
