# Generated by Django 4.0.4 on 2022-06-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyway',
            name='description',
        ),
        migrations.AddField(
            model_name='postapplyway',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
