# Generated by Django 4.0.4 on 2022-07-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_applyway_description_postapplyway_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_of_back',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_front',
            field=models.CharField(max_length=50),
        ),
    ]
