# Generated by Django 4.0.4 on 2022-07-01 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_number_of_back_alter_post_number_of_front'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'flavors',
            },
        ),
        migrations.CreateModel(
            name='PostFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postflavors', to='posts.flavor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postflavors', to='posts.post')),
            ],
            options={
                'db_table': 'postflavors',
            },
        ),
    ]
