# Generated by Django 4.0.4 on 2022-06-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_google_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub', models.CharField(max_length=400)),
                ('image_url', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'google_social_accounts',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.googlesocialaccount'),
        ),
    ]
