# Generated by Django 4.0.4 on 2022-06-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_googlesocialaccount_remove_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='google_id',
            new_name='google_account',
        ),
    ]
