# Generated by Django 4.0.4 on 2022-06-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_google_id_user_google_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.googlesocialaccount', unique=True),
        ),
    ]
